apiVersion: v1
kind: Service
metadata:
  name: frontend-svc                 # DNS: frontend-svc.three-tier-app.svc.cluster.local
  namespace: three-tier-app
  labels:
    app: frontend
    tier: web
spec:
  type: ClusterIP                    # Internal only, accessed via Ingress
  ports:
    - port: 3001                     # Service port
      targetPort: 3000               # Container port
      protocol: TCP
      name: http
  selector:
    app: frontend