apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/rahulkarki312/three-tier-app.git
    targetRevision: main
    path: k8s/overlays/development
    
  destination:
    server: https://kubernetes.default.svc
    namespace: three-tier-app
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true