apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: three-tier-app
spec:
  redirectScheme:
    scheme: https
    permanent: true                  # 301 redirect (browser caches it)
    port: "443"